version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome:latest
    platform: linux/amd64
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - NODE_MAX_INSTANCES=3        # If not set, tests won't be concurrently run
      - NODE_MAX_SESSION=3
    depends_on:
      - selenium-hub
    ports:
      - "6900:5900"
    expose:
      - 5555
    networks:
      - selenium-grid

#  tests:
#    build: .
#    depends_on:
#      - selenium-hub
#      - chrome
#    environment:
#      - SELENIUM_HUB=http://selenium-hub:4444/wd/hub




#  selenium-chrome:
#    container_name: selenium-chrome
#    image: selenium/node-chrome:latest
#    platform: linux/amd64
#    volumes:
#      - /dev/shm:/dev/shm
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - NODE_MAX_INSTANCES=3        # If not set, tests won't be concurrently run
#      - NODE_MAX_SESSION=3
#    depends_on:
#      - selenium-hub
#    ports:
#      - "6900:5900"
#    expose:
#      - 5555
#
#    networks:
#      - selenium-grid



#  edge:
#    image: selenium/node-edge
#    platform: linux/amd64
#    volumes:
#      - /dev/shm:/dev/shm
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#    depends_on:
#      - selenium-hub
#
#    ports:
#      - "6902:5900"
#    networks:
#      - selenium-grid

networks:
  selenium-grid:


# Steps to run
# docker-compose up -d
# docker build -t build-image-name .
# docker run --network <networkname>  <imagename>
